Ragoha/AcctMgmt-Frontend

- src/component/user/ConfigComponent.js
- src/css/font.css
> fix. 예산환경설정

- src/component/common/DialogComponent.js
- src/component/mgmt/CoMgmtComponent.js
- src/service/CompanyService.js
> feat. 회사관리 초기화면

- src/component/common/DialogComponent.js
- src/component/mgmt/CoMgmtComponent.js
- src/component/mgmt/DeptMgmtComponent.js
- src/index.js
- src/service/CompanyService.js
> feat. 회사 초기화면

- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/budget/BudgetInitCarryForwordComponent.js
- src/component/budget/DatGridComponent.js
- src/component/common/DialogComponent.js
- src/component/common/MainListItems.js
- src/component/mgmt/CoMgmtComponent.js
- src/component/user/LoginComponent.js
- src/component/user/SignUpComponent.js
- src/index.js
- src/router/MainRouter.js
- src/service/BgtICFService.js
- src/service/CompanyService.js
- src/store/index.js
> fix 230725_ver2 예산과목등록

- src/component/mgmt/CoMgmtComponent.js
> fix. test2

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDTreeGrid.js
- src/component/bgtcd/TreeTest.js
> fix 예산과목등록 230726

- src/component/mgmt/CoMgmtComponent.js
- src/component/mgmt/dialog/CoDialogComponent.js
- src/service/CompanyService.js
> feat. 포커스수정 및 검색창

- src/component/mgmt/DeptMgmtComponent.js
- src/component/mgmt/DivMgmtComponent.js
- src/router/MainRouter.js
- src/service/CompanyService.js
> feat. 기수 구현

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/store/BgtCDBox.js
- src/store/store.js
> fix 예산과목등록 230801

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 회사화면 수정

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfoFormControl.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDSubReg.js
- src/service/BgtCDService.js
- src/store/BgtCDStore.js
> fix예산과목등록 230804 예산그룹등록모달추가

- src/component/bgtcd/BgtCD.js
- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/CoDialogComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/CompanyService.js
- src/service/GisuService.js
> feat. 회사선택구현

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
- src/service/BgtCDService.js
> fix 예산과목등록 230804 CRUD 토큰 적용

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/CompanyService.js
- src/service/DivsService.js
> feat. 사업장 redux 적용 중

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDetailInfoFormControl.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
- src/service/BgtCDService.js
예산그룹조회
- 모달창css 수정
- 예산그룹 데이터 출력 기능 추가
- row 추가 기능 구현(진행중) 상세정보
- DatePicker 데이터 추가
> fix 예산과목등록 230807

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/dept/dialog/AddressComponent.js
- src/component/dept/dialog/DeptDialogComponent.js
- src/service/DeptService.js
> feat. 부서화면 조회

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/service/BgtCDService.js
fix 예산과목등록 230808 TreeViewInsert 기능 작업중
> fix 예산과목등록 230808 TreeViewInsert 기능 작업중

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> fix. 화면 텍스트필드 수정

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/CompanyService.js
- src/service/DeptService.js
- src/service/DivsService.js
> feat. dept 페이지 구현

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDetailInfoFormControl.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
> fix 예산과목등록 230811 예산그룹등록 수정

- src/component/dept/DeptMgmtComponent.js
- src/service/DeptService.js
> feat. 부서crud 구현

- src/component/pjt/dialog/PgrDialogComponent.js
> fix. 프로젝트등록

- src/component/dialog/ForgotPasswordDialog.js
- src/component/dialog/SignUpDialog.js
- src/component/pjt/PjtComponent.js
- src/component/pjt/dialog/PjtDialogComponent.js
- src/component/user/SignUpComponent.js
> fix.회원가입, 프로젝트등록

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDetailInfoFormControl.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
- src/service/BgtCDService.js
> fix 예산과목등록 230814 예산그룹등록추가

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/CoDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/dept/dialog/DeptDialogComponent.js
- src/component/div/DivMgmtComponent.js
- src/component/div/dialog/DivDialogComponent.js
- src/service/CompanyService.js
- src/service/DeptService.js
- src/service/DivsService.js
> feat. 검색기능 및 화면수정

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDSubSearch.js
- src/service/BgtCDService.js
> fix 예산과목등록 230814 검색조건 작업 중

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/CoDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/dept/dialog/DeptDialogComponent.js
- src/component/div/DivMgmtComponent.js
- src/component/div/dialog/DivDialogComponent.js
> feat. 검색기능 수정

- src/component/common/MainComponent.js
- src/component/common/UserInfo.js
- src/component/user/SignUpComponent.js
> fix.메인화면, 회원가입

- package-lock.json
- package.json
- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/DivsService.js
> feat. 회사코드 입력수정

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 예외상황 처리

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/common/SnackBarComponent.js
- src/service/BgtCDService.js
fix 예산과목등록 230819 DATAGRID CRUD 90% 완성
> fix 예산과목등록 230819 DATAGRID CRUD 90% 완성

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/GisuDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 부서트리뷰 포커스

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDetailInfoFormControl.js
- src/service/BgtCDService.js
> fix 예산과목등록 230820 DataGrid 수정

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
- src/component/bgtcd/modal/BgtCDSubSearch.js
- src/component/bgtcd/modal/BgtGrSearch.js
- src/service/BgtCDService.js
-세부항목 추가시 최초데이터값 이상하게 들어감 —> [완료]
- 삭제시 confirm이 먼저 뜨고 -> 삭제기능 . //- > 삭제시 해당 값을 부모로 갖는거 말고도 태영이형 테이블에서 bgtCd값을 사용 중이면 삭제 안되게   —>삭제시 재조회까지[완료]
- placeholder 코드명 —>[완료]
- 예산그룹 200 / enter 눌렀을때 초기화되서 들어가게 —>[완료]
- 저장 - 삭제 문구 통일 —> [완료]
- 예산그룹레벨 수정시 수정완료 스낵바  —> [완료]
- 모든 다이얼로그 검색기능 타이핑 기능 가능하도록—>[완료]
> fix 예산과목등록 230821 수정사항1 (노션참고)

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/CoDialogComponent.js
- src/component/co/dialog/GisuDialogComponent.js
- src/component/common/CustomSwal.js
- src/component/dept/DeptMgmtComponent.js
- src/component/dept/dialog/DeptDialogComponent.js
- src/component/div/DivMgmtComponent.js
- src/component/div/dialog/DivDialogComponent.js
> feat. 부서 트리뷰 수정

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDSubSearch.js
- src/component/bgtcd/modal/BgtGrSearch.js
fix 예산과목등록 230821 수정사항2 (노션참고)
> fix 예산과목등록 230821 수정사항2 (노션참고)

- src/component/pjt/PjtComponent.js
- src/component/user/LoginComponent.js
- src/component/user/SignUpComponent.js
- src/css/font.css
- src/storage/Cookie.js
> fix.로그인, 프로젝트등록,회원가입, 쿠기

- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/GisuDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 검색수정

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/GisuDialogComponent.js
> feat. gisu예외처리

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/GisuDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 검색조회버튼 수정

- src/component/co/CoMgmtComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/CompanyService.js
- src/service/DeptService.js
- src/service/DivsService.js
> feat. url 수정

- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
> feat. 사업장&부서 초기화면수정

- src/component/dept/DeptMgmtComponent.js
- src/component/div/DivMgmtComponent.js
- src/service/CompanyService.js
- src/service/DivsService.js
> feat. url재수정

- src/component/co/CoMgmtComponent.js
- src/component/co/dialog/CoDialogComponent.js
- src/component/dept/DeptMgmtComponent.js
- src/component/dept/dialog/DeptDialogComponent.js
- src/component/div/DivMgmtComponent.js
- src/component/div/dialog/DivDialogComponent.js
- src/service/DeptService.js
- src/service/DivsService.js
> feat. 예외처리

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
> fix 예산과목등록 추가 수정

- src/component/bgtcd/BgtCD.js
- src/component/bgtcd/BgtCDDatagrid.js
- src/component/bgtcd/BgtCDDetailInfo.js
- src/component/bgtcd/BgtCDDropDownBox.js
- src/component/bgtcd/modal/BgtCDAddSubDialog.js
- src/component/bgtcd/modal/BgtCDDevFgCustom.js
- src/component/bgtcd/modal/BgtCDSubSearch.js
fix 예산과목등록 230829 자잘한 text 및 require 색
> fix 예산과목등록 230829 자잘한 text 및 require 색 
